# Generated by Django 4.2.2 on 2024-09-23 11:29

import article.models.video
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها ',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان دوره')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('publish_status', models.CharField(choices=[('completed', 'تکمیل شده'), ('inprogress', 'درحال تکمیل')], default='inprogress', max_length=15, verbose_name='وضعیت انتشار دوره')),
                ('is_active', models.BooleanField(verbose_name='دوره منتشر شود')),
                ('is_free', models.BooleanField(default=False, verbose_name='دوره رایگان است')),
                ('price', models.PositiveIntegerField(blank=True, help_text='به تومان', null=True, verbose_name='هزینه دوره')),
                ('image', models.ImageField(upload_to='thumbnails/', verbose_name='تصویر')),
                ('slug', models.SlugField(help_text='slug', unique=True, verbose_name='نامک')),
                ('prerequisite', models.TextField(blank=True, null=True, verbose_name='پیش نیاز های دوره')),
                ('time_of_course', models.DurationField(help_text='HH:MM:SS', verbose_name='مدت زمان دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('SuggestedCourses', models.ManyToManyField(blank=True, to='article.course', verbose_name='دوره پیشنهادی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('category', models.ManyToManyField(related_name='articles', to='article.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دوره ',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب آزمون ')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان آزمون')),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.CharField(default='quiz', editable=False, max_length=10, verbose_name='نوع')),
                ('publish', models.BooleanField(default=True, verbose_name='آیا منتشر شود')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='article.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها ',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب ')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فیلم')),
                ('video_description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('publish', models.BooleanField(default=False, verbose_name=' انتشار')),
                ('is_free', models.BooleanField(default=False, verbose_name=' رایگان')),
                ('duration', models.DurationField(blank=True, help_text='HH:MM:SS', null=True, verbose_name='مدت زمان ویدیو')),
                ('videofile', models.FileField(help_text='.mp4, .mkv', null=True, upload_to=article.models.video.video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])], verbose_name='ویدیو')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to=article.models.video.video_path, verbose_name='تامبنیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='video', editable=False, max_length=10, verbose_name='نوع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='article.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها ',
            },
        ),
        migrations.CreateModel(
            name='QuizProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrects', models.PositiveIntegerField(default=0, verbose_name='درست ها')),
                ('incorrects', models.PositiveIntegerField(default=0, verbose_name='درست ها')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز کل')),
                ('is_done', models.BooleanField(default=False, verbose_name='آزمون انجام شده است؟')),
                ('choices', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='گزینه های انتخاب شده توسط کاربر')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.quiz', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب سوالات ')),
                ('question', models.TextField(null=True, verbose_name='سوال')),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='گزینه اول')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='گزینه دوم')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='گزینه سوم')),
                ('op4', models.CharField(max_length=200, null=True, verbose_name='گزینه چهارم')),
                ('ans', models.CharField(choices=[('op1', 'گزینه اول '), ('op2', 'گزینه دوم '), ('op3', 'گزینه سوم '), ('op4', 'گزینه چهارم ')], max_length=200, null=True, verbose_name='پاسخ')),
                ('publish', models.BooleanField(default=True, verbose_name='آیا منتشر شود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='article.quiz', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها ',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سایت')),
                ('image', models.ImageField(upload_to='homepageheader/', verbose_name='تصویر header')),
                ('description', models.TextField(verbose_name='توضیحات سایت')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='تصویر header')),
                ('banner2_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner2_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='تصویر header')),
                ('banner2_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_2', to='article.course', verbose_name='دوره یک ')),
                ('banner_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_1', to='article.course', verbose_name=' دوره دو')),
            ],
            options={
                'verbose_name': 'خانه',
                'verbose_name_plural': 'خانه',
            },
        ),
    ]
